"""auto generate ph num

Revision ID: dc2e49a4daeb
Revises: 57a2911c15c0
Create Date: 2026-01-14 23:57:06.775509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2e49a4daeb'
down_revision: Union[str, Sequence[str], None] = '57a2911c15c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users1', sa.Column('phone_num', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users1', 'phone_num')
    # ### end Alembic commands ###
